---
- name: Add nodes
  become: true
  lineinfile:
    path: /etc/hadoop/conf/slaves
    line: "{{ item }}"
  with_items:
    - 'data-1'
    - 'data-2'
    - 'data-3'

- name: Format HDFS
  raw: sudo -u hdfs hadoop namenode -format

- name: Start Hadoop
  raw: sudo service hadoop-hdfs-namenode start
