---
- name: Python Bootstrap for Ansible
  raw: sudo apt autoremove -y -q 2> /dev/null && sudo apt-get install -f -y -q python3 python3-setuptools 2> /dev/null && sudo ln -s /usr/bin/python3 /usr/bin/python 2> /dev/null && sudo easy_install3 pip py4j 2> /dev/null

- name: Apt Packages - Java
  become: true
  apt:
    name: openjdk-8-jre
    state: present

- name: Apt Packages - Scala
  become: true
  apt:
    name: scala
    state: present

- name: Add hadoop to path
  become: true
  lineinfile:
    path: /etc/environment
    regexp: '^PATH='
    line: 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/hadoop-2.7.4/bin'

- name: Add JAVA_HOME
  become: true
  lineinfile:
    path: /etc/environment
    line: 'JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre'

- name: Add HADOOP_HOME
  become: true
  lineinfile:
    path: /etc/environment
    line: 'HADOOP_HOME=/usr/lib/hadoop'

- name: Add HADOOP_LIBEXEC_DIR
  become: true
  lineinfile:
    path: /etc/environment
    line: 'HADOOP_LIBEXEC_DIR=/usr/lib/hadoop/libexec'
